# Generated by Django 2.2.24 on 2021-10-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_userdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
